//tarkistettu 180105

#ifndef CONFLOAD_CPP
#define CONFLOAD_CPP

//#include <stdio.h>
#include <string.h>
#include "atsplugin.h"

#define LINE_LENGTH 1023
#define COMMAND_LENGTH 40


enum PLUGIN_OPTIONS {
SYSTEM = 0, AWSINDICATOR, AWSWARNINGSOUND, AWSCLEARSOUND, AWSACKNOWLEDGEKEY, AWSMINSPEED,
AWSDELAY, AWSINDICATORAPPEAR, AWSBRAKECANCEL, TPWSINDICATOR, TPWSINDICATOR2, TPWSINDICATOR3,
TPWSWARNINGSOUND, TPWSRESETKEY, TPWSOVERRIDEKEY, TPWSSTOPDELAY, TPWSOVERRIDELIFETIME,
TPWSBRAKECANCEL, STARTUPTEST,

//speedcontrol
OVERSPEEDCONTROL, WARNINGSPEED, OVERSPEED, SAFESPEED, OVERSPEEDINDICATOR, OVERSPEEDALARM,

//vigilance
VIGILANCE, VIGILANCELAMP, VIGILANCEALARM, VIGILANCEKEY, VIGILANCEINTERVAL, VIGILANCEDELAY1,
VIGILANCEDELAY2, INDEPENDENTVIGILANCE, VIGILANCEINACTIVESPEED,
VIGILANCECANCELLABLE, VIGILANCEAUTORELEASE,

//power
POWERGAPBEHAVIOUR, POWERPICKUPPOINTS, POWERINDICATOR,
DOORPOWERLOCK, DOORAPPLYBRAKE, TRACTIONINTERLOCK, NEUTRALRVRBRAKE,
REVERSERCONTROL, REVERSERINDEX, EFFECTIVERVRINDEX,
REMINDERINDICATOR, REMINDERKEY,

//windshield
WIPERINDEX, WIPERRATE, WIPERHOLDPOSITION, WIPERDELAY, WIPERONKEY,
WIPEROFFKEY, WIPERSOUND, DROPSTARTINDEX, NUMBEROFDROPS, DROPSOUND,

//misc
TRAVELMETERMODE, TRAVELMETER100, TRAVELMETER10, TRAVELMETER1, TRAVELMETER01, TRAVELMETER001,

//traction
TRACTION, AUTOMATIC, AUTOMATICINDICATOR,
AMMETER, AMMETERVALUES, FUELCONSUMPTION, FUELCAPACITY, FUELSTARTAMOUNT, FUELFILLSPEED,
FUELINDICATOR, GEARRATIOS, GEARFADEINRANGE, GEARFADEOUTRANGE, GEARINDICATOR, GEARUPKEY,
GEARDOWNKEY, GEARCHANGESOUND, TACHOMETER, HEATINGPART, HEATINGRATE, OVERHEATWARN, OVERHEAT,
OVERHEATRESULT, THERMOMETER, OVERHEATINDICATOR, OVERHEATALARM,

//steam
CUTOFFMAX, CUTOFFMIN, CUTOFFINEFFECTIVE, CUTOFFRATIOBASE, CUTOFFRATIO, CUTOFFDEVIATION,
CUTOFFINCREASEKEY, CUTOFFDECREASEKEY, CUTOFFCHANGESPEED, CUTOFFINDICATOR,
REGULATORPRESSUREUSE, /*CUTOFFPRESSUREUSE,*/
BOILERMAXPRESSURE, BOILERMINPRESSURE, BOILERBLOWOFFPRESSURE, BOILERPRESSUREINDICATOR,
BOILERMAXWATERLEVEL, BOILERWATERTOSTEAMRATE, BOILERWATERLEVELINDICATOR,
INJECTORRATE, INJECTORINDICATOR, INJECTORTOGGLEKEY,

DOORINDICATOR, KLAXONINDICATOR, GEARLOOPSOUND, FUELFILLINDICATOR, CUSTOMINDICATORS,

NUM_PLUGIN_OPTIONS
};

extern char commands[NUM_PLUGIN_OPTIONS][COMMAND_LENGTH];


struct PLUGIN_OPTION
{
	int v;
	PLUGIN_OPTION *next;
};

extern PLUGIN_OPTION gOpts[NUM_PLUGIN_OPTIONS];


void SetDefaults();
bool LoadConfig();
void ScrapConfig();


#endif

